var cacheName = "safraland-project-cache-v1"
var assets = [
    "./",
    "CinemaStation.html",
    "CinemaStationStartPage.html",

    "DataTable.html",

    "DimotStation.html",
    "DimotStationStartPage.html",

    "Diploma.html",

    "EducationalStation.html",
    "EducationalStationStartPage.html",

    "FoodStation.html",
    "FoodStationStartPage.html",

    "GamimgStationStartPage.html",
    "GamingStation.html",

    "Login.html",
    "Map.html",

    "MusicStation.html",
    "MusicStationStartPage.html",

    "MyWorldStation.html",
    "MyWorldtStationStartPage.html",

    "PhotoAlbumPage.html",
    "Registration.html",
    "SettingsPage.html",

    "TreatmentStation.html",
    "TreatmentStationStartPage.html",


    "css/style.css",
    "css/bootstrap.rtl.min.css",

    "jScripts/main.js",
    "jScripts/bootstrap.bundle.js",
    "jScripts/qrScript.js",

    "images/activitiesProgressBarUncompleted.svg",
    "images/activityProgressBar.svg",
    "images/arrow.svg",
    "images/bronzeMedal.svg",
    "images/bubbleTextBig.svg",
    "images/bubbleTextNarrow.svg",
    "images/bubbleTextWider.svg",
    "images/clockIcon.svg",
    "images/clockIconWhite.svg",
    "images/footStepsIcon.svg",
    "images/footStepsIconWhite.svg",
    "images/goldMedal.svg",
    "images/hitLogo.svg",
    "images/lampIcon.svg",
    "images/logo.png",
    "images/penguinHandUp.svg",
    "images/penguinHandUpOnly.svg",
    "images/rectanglePhotoAlbum.svg",
    "images/safraLogo.png",
    "images/silverMedal.svg",
    "images/star.svg",
    "images/videoIcon.svg",
   

    "images/backgrounds/aboutUsBackground.svg",
    "images/backgrounds/aboutUsBackgroundPhone.svg",
    "images/backgrounds/background.svg",
    "images/backgrounds/diplomaBackground.svg",
    "images/backgrounds/finishStationBackground.svg",
    "images/backgrounds/mapBackground.svg",
    "images/backgrounds/popUpBackgroudBigger.svg",
    "images/backgrounds/popUpBackground.svg",
    "images/backgrounds/popupMedalsBackground.svg",
    "images/backgrounds/popupScanQrCode.svg",
    "images/backgrounds/popupWellDone.svg",
    "images/backgrounds/shortWhiteCard.svg",
    "images/backgrounds/startStationBackground.svg",
    "images/backgrounds/titleSign.svg",
    "images/backgrounds/wellDoneSmall.svg",

    "images/buttons/audioBtn.svg",
    "images/buttons/cameraBtn.svg",
    "images/buttons/checkBtn.svg",
    "images/buttons/confirmBtn.svg",
    "images/buttons/deleteBtn.svg",
    "images/buttons/galleryBtn.svg",
    "images/buttons/galleryBtnSmall.svg",
    "images/buttons/infoBtn.svg",
    "images/buttons/logoutBtn.svg",
    "images/buttons/mapBtn.svg",
    "images/buttons/nextBtn.svg",
    "images/buttons/noBtn.svg",
    "images/buttons/playAgainBtn.svg",
    "images/buttons/playGame.svg",
    "images/buttons/questionMarkBtn.svg",
    "images/buttons/registrationBtn.svg",
    "images/buttons/replayBtn.svg",
    "images/buttons/resetStationBtn.svg",
    "images/buttons/saveChangesBtn.svg",
    "images/buttons/scanQrCodeBtn.svg",
    "images/buttons/sendBtn.svg",
    "images/buttons/settingsBtn.svg",
    "images/buttons/shareBtn.svg",
    "images/buttons/skipBtn.svg",
    "images/buttons/toTheGame.svg",
    "images/buttons/toTheMapBtn.svg",
    "images/buttons/toThePractice.svg",
    "images/buttons/xBtn.svg",
    "images/buttons/yesBtn.svg",

    "images/characters/bunnyCharacter.svg",
    "images/characters/catCharacter.svg",
    "images/characters/lionCharacter.svg",
    "images/characters/penguinCharacter.svg",
    "images/characters/teddyBearCharacter.svg",

    "images/cinemaStation/cinemaStationSign.svg",
    "images/cinemaStation/enthusiasticDistractor.svg",
    "images/cinemaStation/enthusiasticExpression.png",
    "images/cinemaStation/finishCinemaStationSign.svg",
    "images/cinemaStation/happinessDistractor.svg",
    "images/cinemaStation/happyExpression.png",
    "images/cinemaStation/madExpression.png",
    "images/cinemaStation/madnessDistractor.svg",
    "images/cinemaStation/popupCorrectAnswerCinema.svg",
    "images/cinemaStation/sadExpression.png",
    "images/cinemaStation/sadnessDistractor.svg",
    "images/cinemaStation/surpriseDistractor.svg",

    "images/dimotStation/carAfterScanning.svg",
    "images/dimotStation/carBeforeScanning.svg",
    "images/dimotStation/dimotStationSign.svg",
    "images/dimotStation/finishDimotStationSign.svg",
    "images/dimotStation/handAfterScanning.svg",
    "images/dimotStation/handBeforeScanning.svg",
    "images/dimotStation/legAfterScanning.svg",
    "images/dimotStation/legBeforeScanning.svg",
    "images/dimotStation/missile.svg",
    "images/dimotStation/MRIMachine.svg",
    "images/dimotStation/MRIOption.svg",
    "images/dimotStation/phoneAfterScanning.svg",
    "images/dimotStation/phoneBeforeScanning.svg",
    "images/dimotStation/popupCorrectAnswerDimot.svg",
    "images/dimotStation/pose1.png",
    "images/dimotStation/pose2.png",
    "images/dimotStation/pose3.png",
    "images/dimotStation/poseWhiteCard.svg",
    "images/dimotStation/timer.svg",
    "images/dimotStation/timerBackgroundOn.svg",
    "images/dimotStation/ultrasoundMachine.svg",
    "images/dimotStation/ultrasoundOption.svg",
    "images/dimotStation/xRayMachine.svg",
    "images/dimotStation/xRayOption.svg",


    "images/educationalStation/breathe.svg",
    "images/educationalStation/breathingAnimationCounter.gif",
    "images/educationalStation/breathingAnimationPart1.gif",
    "images/educationalStation/breathingAnimationPart2.gif",
    "images/educationalStation/breathingAnimationPart3.gif",
    "images/educationalStation/breathingAnimationPart4.gif",
    "images/educationalStation/breathingGifCard.gif",
    "images/educationalStation/educationalStationSign.svg",
    "images/educationalStation/familiy.svg",
    "images/educationalStation/finishEducationalStationSign.svg",
    "images/educationalStation/laugh.svg",
    "images/educationalStation/learnAboutTheTest.svg",
    "images/educationalStation/listenToSongs.svg",
    "images/educationalStation/progressBar.gif",
    "images/educationalStation/whiteCard.svg",



    "images/foodStation/apple.svg",
    "images/foodStation/bagel.svg",
    "images/foodStation/baguetteBig.svg",
    "images/foodStation/baguetteSmall.svg",
    "images/foodStation/banana.svg",
    "images/foodStation/cake.svg",
    "images/foodStation/carbohydratesGroup.svg",
    "images/foodStation/carbohydratesLabel.svg",
    "images/foodStation/carrot.svg",
    "images/foodStation/challah.svg",
    "images/foodStation/cheese.svg",
    "images/foodStation/corn.svg",
    "images/foodStation/cottage.svg",
    "images/foodStation/cucumber.svg",
    "images/foodStation/egg.svg",
    "images/foodStation/fatsGroup.svg",
    "images/foodStation/fatsLabel.svg",
    "images/foodStation/finishFoodStationSign.svg",
    "images/foodStation/fish.svg",
    "images/foodStation/foodBags.svg",
    "images/foodStation/foodForPhoto.svg",
    "images/foodStation/foodlStationSign.svg",
    "images/foodStation/foodPyramidCarbohydrates.svg",
    "images/foodStation/foodPyramidFats.svg",
    "images/foodStation/foodPyramidProteins.svg",
    "images/foodStation/foodPyramidSweets.svg",
    "images/foodStation/foodPyramidVitamins.svg",
    "images/foodStation/gamba.svg",
    "images/foodStation/greenGrapes.svg",
    "images/foodStation/greenQuarter.svg",
    "images/foodStation/halfFoodPyramidCarbohydrates.svg",
    "images/foodStation/halfFoodPyramidFats.svg",
    "images/foodStation/halfFoodPyramidProteins.svg",
    "images/foodStation/halfFoodPyramidSweets.svg",
    "images/foodStation/halfFoodPyramidVitamins.svg",
    "images/foodStation/hamburger.svg",
    "images/foodStation/hamburgerBun.svg",
    "images/foodStation/hotDog.svg",
    "images/foodStation/lettuce.svg",
    "images/foodStation/milk.svg",
    "images/foodStation/mushrooms.svg",
    "images/foodStation/orange.svg",
    "images/foodStation/orangeQuarter.svg",
    "images/foodStation/pasta.svg",
    "images/foodStation/peach.svg",
    "images/foodStation/pear.svg",
    "images/foodStation/plate.svg",
    "images/foodStation/plateAndTablecloth.svg",
    "images/foodStation/popupCorrectAnswersFoodPyramid.svg",
    "images/foodStation/proteinsGroup.svg",
    "images/foodStation/proteinsLabel.svg",
    "images/foodStation/purpleGrapes.svg",
    "images/foodStation/redQuarter.svg",
    "images/foodStation/rice.svg",
    "images/foodStation/sardines.svg",
    "images/foodStation/smallShelf.svg",
    "images/foodStation/spelledBread.svg",
    "images/foodStation/steak.svg",
    "images/foodStation/strawberry.svg",
    "images/foodStation/sweetsGroup.svg",
    "images/foodStation/sweetsLabel.svg",
    "images/foodStation/tomato.svg",
    "images/foodStation/vegetablesAndFruitsShelf.svg",
    "images/foodStation/vitaminsGroup.svg",
    "images/foodStation/watermelon.svg",
    "images/foodStation/yogurt.svg",



    "images/gamingStation/assemblyGames.svg",
    "images/gamingStation/backCard.svg",
    "images/gamingStation/ballGames.svg",
    "images/gamingStation/boxGames.svg",
    "images/gamingStation/cardGames.svg",
    "images/gamingStation/characterGames.svg",
    "images/gamingStation/finishGamingStationSign.svg",
    "images/gamingStation/gamingStationSign.svg",
    "images/gamingStation/hole.svg",
    "images/gamingStation/imaginationGames.svg",
    "images/gamingStation/injector.svg",
    "images/gamingStation/mask.svg",
    "images/gamingStation/miniCards.svg",
    "images/gamingStation/miniMoles.svg",
    "images/gamingStation/mole.svg",
    "images/gamingStation/moleSmall.svg",
    "images/gamingStation/multiCards.svg",
    "images/gamingStation/pills.svg",
    "images/gamingStation/plaster.svg",
    "images/gamingStation/stethoscope.svg",
    "images/gamingStation/testTube.svg",
    "images/gamingStation/videoGames.svg",
    "images/gamingStation/whackAMoleExample.svg",



    "images/loginPage/letsContinue.svg",

    "images/mapPage/bubleTextMap.svg",
    "images/mapPage/cinemaKidsStation.svg",
    "images/mapPage/dimotStation.svg",
    "images/mapPage/educationalRoom.svg",
    "images/mapPage/foodStation.svg",
    "images/mapPage/galleryBtnSmall.svg",
    "images/mapPage/gamingStation.svg",
    "images/mapPage/linesBackground.svg",
    "images/mapPage/MapProgressBarUncompleted.svg",
    "images/mapPage/musicStation.svg",
    "images/mapPage/myRoomStation.svg",
    "images/mapPage/settingsBtn.svg",
    "images/mapPage/StarProgressBar.svg",
    "images/mapPage/treatmentRoom.svg",



    "images/musicStation/earphones.svg",
    "images/musicStation/finishMusicStationSign.svg",
    "images/musicStation/musicalNotes.svg",
    "images/musicStation/musicalInstruments.svg",
    "images/musicStation/musicStationSign.svg",
    "images/musicStation/popupCorrectAnswerMusic.svg",
    "images/musicStation/speakers.svg",

    "images/musicStation/faces/calmFace.svg",
    "images/musicStation/faces/happyFace.svg",
    "images/musicStation/faces/sadFace.svg",

    "images/musicStation/musicalInstruments/bell.svg",
    "images/musicStation/musicalInstruments/drum.svg",
    "images/musicStation/musicalInstruments/guitar.svg",
    "images/musicStation/musicalInstruments/piano.svg",
    "images/musicStation/musicalInstruments/trumpet.svg",
    "images/musicStation/musicalInstruments/xylophone.svg",



    "images/myWorldStation/auxiliaryForceBed.svg",
    "images/myWorldStation/auxiliaryForceDistractor.svg",,
    "images/myWorldStation/auxiliaryForceFood.svg",
    "images/myWorldStation/auxiliaryForceShower.svg",
    "images/myWorldStation/auxiliaryForceTitle.svg",
    "images/myWorldStation/ballons.svg",
    "images/myWorldStation/ballonsFrame.svg",
    "images/myWorldStation/ballonsSticker.svg",
    "images/myWorldStation/ballonsTag.svg",
    "images/myWorldStation/bed.svg",
    "images/myWorldStation/bedAndinfusion.svg",
    "images/myWorldStation/bedFrame.svg",
    "images/myWorldStation/bedSticker.svg",
    "images/myWorldStation/bedTag.svg",
    "images/myWorldStation/disinfectant.svg",
    "images/myWorldStation/disinfectantFrame.svg",
    "images/myWorldStation/disinfectantSticker.svg",
    "images/myWorldStation/disinfectantTag.svg",
    "images/myWorldStation/doctor.svg",
    "images/myWorldStation/doctors.svg",
    "images/myWorldStation/emergencyButton.svg",
    "images/myWorldStation/emergencyButtonFrame.svg",
    "images/myWorldStation/emergencyButtonSticker.svg",
    "images/myWorldStation/emergencyButtonTag.svg",
    "images/myWorldStation/emptyRoom.svg",
    "images/myWorldStation/finishMyWorldStationSign.svg",
    "images/myWorldStation/imgStorageFrame.svg",
    "images/myWorldStation/infusion.svg",
    "images/myWorldStation/infusionFrame.svg",
    "images/myWorldStation/infusionSticker.svg",
    "images/myWorldStation/infusionTag.svg",
    "images/myWorldStation/medicalStaffDistractor.svg",
    "images/myWorldStation/MedicalStaffTitle.svg",
    "images/myWorldStation/myWorldStationSign.svg",
    "images/myWorldStation/nurse.svg",
    "images/myWorldStation/nurses.svg",
    "images/myWorldStation/patientBoard.svg",
    "images/myWorldStation/patientBoardFrame.svg",
    "images/myWorldStation/patientBoardSticker.svg",
    "images/myWorldStation/patientBoardTag.svg",
    "images/myWorldStation/popupCorrectAnswerMyWorld.svg",
    "images/myWorldStation/roomSign.svg",
    "images/myWorldStation/shadow.svg",
    "images/myWorldStation/sofa.svg",
    "images/myWorldStation/sofaFrame.svg",
    "images/myWorldStation/sofaSticker.svg",
    "images/myWorldStation/sofaTag.svg",



    "images/treatmentStation/bloodTestDistractor.svg",
    "images/treatmentStation/bloodTestTube.svg",
    "images/treatmentStation/bloodTubesAndPlasters.svg",
    "images/treatmentStation/finishTreatmentStationSign.svg",
    "images/treatmentStation/heart.svg",
    "images/treatmentStation/infusion.svg",
    "images/treatmentStation/plaster.svg",
    "images/treatmentStation/popupCorrectAnswerTreatment.svg",
    "images/treatmentStation/scratch.svg",
    "images/treatmentStation/shortWhiteCardTreatment.svg",
    "images/treatmentStation/staffMemberBadge.svg",
    "images/treatmentStation/stethoscope.svg",
    "images/treatmentStation/teddyBear.svg",
    "images/treatmentStation/thermometer.svg",
    "images/treatmentStation/treatmentRoom.svg",
    "images/treatmentStation/treatmentStationSign.svg",



    "images/RegistrationPage/age3_5.svg",
    "images/RegistrationPage/age6_10.svg",
    "images/RegistrationPage/age11_13.svg",
    "images/RegistrationPage/age14_16.svg",
    "images/RegistrationPage/blueBtn.svg",
    "images/RegistrationPage/boy.svg",
    "images/RegistrationPage/girl.svg",
    "images/RegistrationPage/greenBtn.svg",
    "images/RegistrationPage/letsStart.svg",
    "images/RegistrationPage/previousBtn.svg",
    "images/RegistrationPage/previousBtn.svg",
    "images/RegistrationPage/purpleBtn.svg",
    "images/RegistrationPage/redBtn.svg",
    "images/RegistrationPage/step1.svg",
    "images/RegistrationPage/step2.svg",
    "images/RegistrationPage/step3.svg",
    "images/RegistrationPage/yellowBtn.svg",



    "audio/audioBeforeVideo.mp3",
    "audio/finalStep.mp3",
    "audio/finishStationFeedback.mp3",
    "audio/startAgain.mp3",



    "audio/cinemaStation/expressionRecognition1Feedback_cinemaStationRecord.mp3",
    "audio/cinemaStation/expressionRecognition2Feedback_cinemaStationRecord.mp3",
    "audio/cinemaStation/expressionRecognition3Feedback_cinemaStationRecord.mp3",
    "audio/cinemaStation/expressionRecognition4Feedback_cinemaStationRecord.mp3",
    "audio/cinemaStation/startPage_cinemaStation.mp3",
    "audio/cinemaStation/step1_cinemaStation.mp3",
    "audio/cinemaStation/step2_cinemaStation.mp3",
    "audio/cinemaStation/step3_cinemaStation.mp3",
    "audio/cinemaStation/step4_cinemaStation.mp3",
    "audio/cinemaStation/step5_cinemaStation.mp3",
    "audio/cinemaStation/step6_cinemaStation.mp3",
    "audio/cinemaStation/step7_cinemaStation.mp3",
    "audio/cinemaStation/step8_cinemaStation.mp3",
    "audio/cinemaStation/step9_cinemaStation.mp3",


    "audio/dimotStation/alarmClock.mp3",
    "audio/dimotStation/MRI_dimotStation.mp3",
    "audio/dimotStation/rentgen_dimotStation.mp3",
    "audio/dimotStation/step1_dimotStation.mp3",
    "audio/dimotStation/step2_dimotStation.mp3",
    "audio/dimotStation/step4_dimotStation.mp3",
    "audio/dimotStation/step5_dimotStation.mp3",
    "audio/dimotStation/step6_dimotStation.mp3",
    "audio/dimotStation/step7_dimotStation.mp3",
    "audio/dimotStation/step8_dimotStation.mp3",
    "audio/dimotStation/step9_dimotStation.mp3",
    "audio/dimotStation/step10_dimotStation.mp3",
    "audio/dimotStation/step11_dimotStation.mp3",
    "audio/dimotStation/step12_dimotStation.mp3",
    "audio/dimotStation/step13_dimotStation.mp3",
    "audio/dimotStation/step14_dimotStation.mp3",
    "audio/dimotStation/step15_dimotStation.mp3",
    "audio/dimotStation/step16_dimotStation.mp3",
    "audio/dimotStation/step17_dimotStation.mp3",
    "audio/dimotStation/ultrasound_dimotStation.mp3",
    "audio/dimotStation/videoQuesionFeedback_dimotStation.mp3",
    

    "audio/educationalStation/breathingAnimationFeedback_educationalStation.mp3",
    "audio/educationalStation/breathingCard_educationalStation.mp3",
    "audio/educationalStation/startPage_educationalStation.mp3",
    "audio/educationalStation/step1_educationalStation.mp3",
    "audio/educationalStation/step2_educationalStation.mp3",
    "audio/educationalStation/step3_educationalStation.mp3",
    "audio/educationalStation/step4_educationalStation.mp3",
    "audio/educationalStation/step5_educationalStation.mp3",
    "audio/educationalStation/step6_educationalStation.mp3",
    "audio/educationalStation/step7_educationalStation.mp3",
    "audio/educationalStation/step8_educationalStation.mp3",
    "audio/educationalStation/step9_educationalStation.mp3",
    "audio/educationalStation/step10_educationalStation.mp3",
    "audio/educationalStation/step11_educationalStation.mp3",


    "audio/foodStation/carbohydratesLevelRecord.mp3",
    "audio/foodStation/fatsLevelRecord.mp3",
    "audio/foodStation/foodPyramidFeedback_foodStation.mp3",
    "audio/foodStation/proteinsLevelRecorn.mp3",
    "audio/foodStation/startPage_foodStation.mp3",
    "audio/foodStation/step1_foodStation.mp3",
    "audio/foodStation/step2_foodStation.mp3",
    "audio/foodStation/step3_foodStation.mp3",
    "audio/foodStation/step4_foodStation.mp3",
    "audio/foodStation/step5_foodStation.mp3",
    "audio/foodStation/step6-9_foodStation.mp3",
    "audio/foodStation/step10_foodStation.mp3",
    "audio/foodStation/step11_foodStation.mp3",
    "audio/foodStation/step12_foodStation.mp3",
    "audio/foodStation/step13_foodStation.mp3",
    "audio/foodStation/step14_foodStation.mp3",
    "audio/foodStation/sweetsLevelRecord.mp3",
    "audio/foodStation/vitaminsLevelRecord.mp3",


    "audio/gamingStation/memoryGameFeedback_gamingStation.mp3",
    "audio/gamingStation/moleGameFeedback_gamingStation.mp3",
    "audio/gamingStation/punchMole.mp3",
    "audio/gamingStation/startPage_gamingStation.mp3",
    "audio/gamingStation/step1_gamingStation.mp3",
    "audio/gamingStation/step2_gamingStation.mp3",
    "audio/gamingStation/step3_gamingStation.mp3",
    "audio/gamingStation/step4_gamingStation.mp3",
    "audio/gamingStation/step5_gamingStation.mp3",
    "audio/gamingStation/step6_gamingStation.mp3",
    "audio/gamingStation/step7_gamingStation.mp3",
    "audio/gamingStation/step8_gamingStation.mp3",
    "audio/gamingStation/step9_gamingStation.mp3",
    "audio/gamingStation/step10_gamingStation.mp3",
    "audio/gamingStation/step11_gamingStation.mp3",


    "audio/musicStation/funnyMusic.mp3",
    "audio/musicStation/guitarMusic.mp3",
    "audio/musicStation/pianoMusic.mp3",
    "audio/musicStation/trumpetsAndDrumsMusic.mp3",
    "audio/musicStation/xylophoneAndGuitarMusic.mp3",

    "audio/musicStation/musicalInstruments/bell.mp3",
    "audio/musicStation/musicalInstruments/drums.mp3",
    "audio/musicStation/musicalInstruments/guitar.mp3",
    "audio/musicStation/musicalInstruments/piano.mp3",
    "audio/musicStation/musicalInstruments/trumpet.mp3",
    "audio/musicStation/musicalInstruments/xylophone.mp3",

    "audio/musicStatio/records/musicalInstrumentFeedback1_musicStation.mp3",
    "audio/musicStatio/records/musicalInstrumentFeedback2_musicStation.mp3",
    "audio/musicStatio/records/musicalInstrumentFeedback3_musicStation.mp3",
    "audio/musicStatio/records/musicalInstrumentFeedback4_musicStation.mp3",
    "audio/musicStatio/records/startPage_musicStation.mp3",
    "audio/musicStation/records/step1_musicStation.mp3",
    "audio/musicStation/records/step2_musicStation.mp3",
    "audio/musicStation/records/step3_musicStation.mp3",
    "audio/musicStation/records/step4_musicStation.mp3",
    "audio/musicStation/records/step5_musicStation.mp3",
    "audio/musicStation/records/step6_musicStation.mp3",
    "audio/musicStation/records/step7_musicStation.mp3",
    "audio/musicStation/records/step8_musicStation.mp3",
    "audio/musicStation/records/step9_musicStation.mp3",
    "audio/musicStation/records/step10-11_musicStation.mp3",
    "audio/musicStation/records/step12-13_musicStation.mp3",


    "audio/myWorldStation/myRoomFeedback_myWorldStation.mp3",
    "audio/myWorldStation/staffQuestionsFeedback1_myWorldStation.mp3",
    "audio/myWorldStation/staffQuestionsFeedback2_myWorldStation.mp3",
    "audio/myWorldStation/staffQuestionsFeedback3_myWorldStation.mp3",
    "audio/myWorldStation/startPage_myWorldStation.mp3",
    "audio/myWorldStation/step1_myWorldStation.mp3",
    "audio/myWorldStation/step2_myWorldStation.mp3",
    "audio/myWorldStation/step3_myWorldStation.mp3",
    "audio/myWorldStation/step4_myWorldStation.mp3",
    "audio/myWorldStation/step5_myWorldStation.mp3",
    "audio/myWorldStation/step6_myWorldStation.mp3",
    "audio/myWorldStation/step7_myWorldStation.mp3",
    "audio/myWorldStation/step8-10_myWorldStation.mp3",
    "audio/myWorldStation/step11_myWorldStation.mp3",
    "audio/myWorldStation/step12_myWorldStation.mp3",


    "audio/treatmentStation/findBloodTubesFeedback_treatmentStation.mp3",
    "audio/treatmentStation/findPlastersFeedback_treatmentStation.mp3",
    "audio/treatmentStation/heartBeatCheckFeedback_treatmentStation.mp3",
    "audio/treatmentStation/heartBeating.mp3",
    "audio/treatmentStation/startPage_treatmentStation.mp3",
    "audio/treatmentStation/plasterOnFeedback_treatmentStation.mp3",
    "audio/treatmentStation/step1_treatmentStation.mp3",
    "audio/treatmentStation/step2_treatmentStation.mp3",
    "audio/treatmentStation/step4_treatmentStation.mp3",
    "audio/treatmentStation/step5_treatmentStation.mp3",
    "audio/treatmentStation/step6_treatmentStation.mp3",
    "audio/treatmentStation/step7_treatmentStation.mp3",
    "audio/treatmentStation/step8_treatmentStation.mp3",
    "audio/treatmentStation/step9_treatmentStation.mp3",
    "audio/treatmentStation/step10_treatmentStation.mp3",
    "audio/treatmentStation/step11_treatmentStation.mp3",
    "audio/treatmentStation/step12_treatmentStation.mp3",
    "audio/treatmentStation/step13_treatmentStation.mp3",
    "audio/treatmentStation/step14_treatmentStation.mp3",
    "audio/treatmentStation/step15_treatmentStation.mp3",
    "audio/treatmentStation/step16_treatmentStation.mp3",
    "audio/treatmentStation/step17_treatmentStation.mp3",
    "audio/treatmentStation/thermometerCheckFeedback_treatmentStation.mp3",
    "audio/treatmentStation/videoQuesionFeedback_treatmentStation.mp3"

]

//בהתקנה/הרצה ראשונה של האתר, נפתח זיכרון מטמון ונוסיף אליו את הקבצים
self.addEventListener("install", installEvent => {
    installEvent.waitUntil(
        caches.open(cacheName).then(cache => {
            cache.addAll(assets)
        })
    )
});


self.addEventListener('fetch', function (e) {
    e.respondWith(
        caches.match(e.request).then(function (response) {
            return response || fetch(e.request);
        })
    );
});
